defmodule SpecLedEx.Realization.BindingTest do
  use ExUnit.Case, async: false
  @moduletag spec: ["specled.binding.dangling_reported", "specled.binding.resolve_beam_first", "specled.binding.resolve_sees_use_generated"]

  alias SpecLedEx.Realization.Binding

  # ---------------------------------------------------------------------------
  # Beam-accessible fixtures
  #
  # `SpecLedEx.Realization.Binding.resolve/2` consults beam debug_info first;
  # that requires the target module to be loaded from a .beam file on disk.
  # We compile fixture sources to a tmp dir, add the dir to the code path, and
  # load the modules from disk so `:code.get_object_code/1` returns their
  # binaries. Modules compiled this way survive for the duration of the VM.
  # ---------------------------------------------------------------------------

  setup_all do
    tmp_dir =
      Path.join(
        System.tmp_dir!(),
        "specled_binding_fixtures_#{:erlang.unique_integer([:positive])}"
      )

    File.mkdir_p!(tmp_dir)

    source_path = Path.join(tmp_dir, "fixtures.ex")

    File.write!(source_path, """
    defmodule SpecLedEx.BindingFixtures.SomeDSL do
      defmacro __using__(_opts) do
        quote do
          def handle_event(_event_name, _payload), do: :ok
        end
      end
    end

    defmodule SpecLedEx.BindingFixtures.PhoenixLikeConsumer do
      use SpecLedEx.BindingFixtures.SomeDSL
    end

    defmodule SpecLedEx.BindingFixtures.SampleHandler do
      def handle_request(verb, path, body) when is_atom(verb) do
        {verb, path, body}
      end
    end
    """)

    previous_cwd = File.cwd!()
    File.cd!(tmp_dir)

    try do
      {:ok, _modules, _warnings} =
        Kernel.ParallelCompiler.compile_to_path([source_path], tmp_dir)
    after
      File.cd!(previous_cwd)
    end

    :code.add_patha(String.to_charlist(tmp_dir))

    for mod <- [
          SpecLedEx.BindingFixtures.SomeDSL,
          SpecLedEx.BindingFixtures.PhoenixLikeConsumer,
          SpecLedEx.BindingFixtures.SampleHandler
        ] do
      :code.purge(mod)
      :code.delete(mod)
      {:module, ^mod} = :code.load_file(mod)
    end

    on_exit(fn ->
      for mod <- [
            SpecLedEx.BindingFixtures.SomeDSL,
            SpecLedEx.BindingFixtures.PhoenixLikeConsumer,
            SpecLedEx.BindingFixtures.SampleHandler
          ] do
        :code.purge(mod)
        :code.delete(mod)
      end

      :code.del_path(String.to_charlist(tmp_dir))
      File.rm_rf!(tmp_dir)
    end)

    {:ok, tmp_dir: tmp_dir}
  end

  describe "parse/1" do
    test "parses standard MFA strings" do
      assert {:ok, {MyMod, :foo, 2}} = Binding.parse("MyMod.foo/2")
    end

    test "parses nested module MFA strings" do
      assert {:ok, {mod, :run, 1}} = Binding.parse("Foo.Bar.Baz.run/1")
      assert mod == Module.concat([Foo.Bar.Baz])
    end

    test "parses module-only bindings" do
      assert {:ok, {:module, MyMod}} = Binding.parse("MyMod")
    end

    test "rejects malformed MFAs" do
      assert {:error, :invalid_mfa, "junk/bad"} = Binding.parse("junk/bad")
      assert {:error, :invalid_mfa, ""} = Binding.parse("")
    end
  end

  describe "resolve/2 — beam first" do
    test "returns {:ok, ast} for a vanilla compiled function" do
      result = Binding.resolve("SpecLedEx.BindingFixtures.SampleHandler.handle_request/3")
      assert {:ok, ast} = result
      refute is_nil(ast)
    end

    test "resolves functions generated via `use SomeDSL` through the beam path" do
      # Source-fallback would miss `handle_event/2` — it's only in expansion.
      result = Binding.resolve("SpecLedEx.BindingFixtures.PhoenixLikeConsumer.handle_event/2")

      assert {:ok, ast} = result,
             "expected beam-first resolver to find handle_event/2 generated by use SomeDSL, got: #{inspect(result)}"

      refute is_nil(ast)
    end
  end

  describe "resolve/2 — dangling" do
    test "returns {:error, :not_found, details} when the MFA exists nowhere" do
      assert {:error, :not_found, details} =
               Binding.resolve("SpecLedEx.BindingFixtures.SampleHandler.missing_fun/0")

      assert details.mfa == "SpecLedEx.BindingFixtures.SampleHandler.missing_fun/0"
      assert is_list(details.searched)
    end

    test "returns {:error, :not_found, details} for a non-existent module" do
      assert {:error, :not_found, details} =
               Binding.resolve("Absolutely.Nothing.Here.missing/1")

      assert details.mfa == "Absolutely.Nothing.Here.missing/1"
    end
  end
end
