defmodule SpecLedEx.Realization.ExpandedBehavior do
  # covers: specled.expanded_behavior_tier.reads_beam_debug_info
  # covers: specled.expanded_behavior_tier.hash_stable_on_refactor
  # covers: specled.expanded_behavior_tier.no_debug_info_detector_unavailable
  # covers: specled.expanded_behavior_tier.mixed_fixture_coverage
  @moduledoc """
  Third realization tier. Hashes the post-macro-expansion AST of each declared
  MFA by pulling `:beam_lib.chunks(beam, [:debug_info])` and canonicalizing the
  `definitions` entry for the target MFA via
  `SpecLedEx.Realization.Canonical.normalize/1`.

  This tier catches drift in functions generated by `use SomeDSL` — the
  expanded AST is what actually runs after compile, regardless of whether the
  clause came from source text or from a macro. It is the authoritative view
  of a subject's behavior.

  When a target module was compiled with `@compile {:no_debug_info, true}` (or
  debug_info is otherwise absent) the tier degrades gracefully: it emits a
  single `detector_unavailable` finding with reason `:debug_info_stripped` per
  offending module and returns no hash. Drift is not asserted for that subject
  on this tier.

  Umbrella graceful degrade mirrors `SpecLedEx.Realization.ApiBoundary`: when
  `opts[:umbrella?]` is true a single `detector_unavailable` finding with
  reason `umbrella_unsupported` is emitted and no binding walk is attempted.
  """

  alias SpecLedEx.Compiler.Context
  alias SpecLedEx.Realization.{Binding, Canonical, HashStore}

  @tier "expanded_behavior"
  @drift_code "branch_guard_realization_drift"
  @dangling_code "branch_guard_dangling_binding"
  @detector_unavailable_code "detector_unavailable"

  @type binding_ref :: %{
          subject_id: String.t(),
          requirement_id: String.t() | nil,
          mfa: String.t()
        }

  @type hash_result ::
          {:ok, binary()}
          | {:error, {:debug_info_stripped, module()}}
          | {:error, {:not_found, map()}}

  @doc """
  Hashes the expanded AST for a single MFA binding.

  Resolves the module's beam, extracts the `definitions` entry for the target
  function+arity from the elixir_v1 debug_info module_map, canonicalizes it
  via `Canonical.normalize/1`, and hashes it via the deterministic
  `term_to_binary` pipeline.

  Returns `{:error, {:debug_info_stripped, module}}` when the module loaded
  but `:beam_lib.chunks/2` reports no debug_info (the `@compile
  {:no_debug_info, true}` path), or `{:error, {:not_found, details}}` for
  unresolvable MFAs.
  """
  @spec hash(String.t(), keyword()) :: hash_result()
  def hash(mfa_string, _opts \\ []) when is_binary(mfa_string) do
    with {:ok, {mod, fun, arity}} <- parse_mfa(mfa_string),
         {:module, ^mod} <- Code.ensure_loaded(mod),
         {:ok, binary} <- beam_binary_for(mod),
         :ok <- ensure_debug_info(mod, binary),
         {:ok, ast} <- extract_expanded_clause(mod, binary, fun, arity, mfa_string) do
      {:ok, Canonical.hash(Canonical.normalize(ast))}
    else
      {:error, {:debug_info_stripped, mod}} ->
        {:error, {:debug_info_stripped, mod}}

      {:error, {:not_found, details}} ->
        {:error, {:not_found, details}}

      {:error, :invalid_mfa} ->
        {:error, {:not_found, %{mfa: mfa_string, reason: :invalid_mfa}}}

      {:error, _reason} ->
        {:error, {:not_found, %{mfa: mfa_string, searched: [:beam]}}}
    end
  end

  @doc """
  Runs the expanded_behavior tier for a list of bindings.

  For each binding we compute the current expanded-behavior hash and compare
  with the committed value in `.spec/state.json`. Emits
  `branch_guard_realization_drift` on mismatch, `branch_guard_dangling_binding`
  when the MFA is unresolvable, and `detector_unavailable
  (reason: debug_info_stripped)` once per module whose debug_info is absent.
  """
  @spec run([binding_ref()], Context.t() | nil, keyword()) :: [map()]
  def run(bindings, context \\ nil, opts \\ []) do
    cond do
      Keyword.get(opts, :umbrella?, false) ->
        [
          %{
            "code" => @detector_unavailable_code,
            "reason" => "umbrella_unsupported",
            "message" =>
              "expanded_behavior tier does not support umbrella apps in v1. " <>
                "Re-run per umbrella child app or wait for v1.1."
          }
        ]

      true ->
        root = Keyword.get(opts, :root, File.cwd!())
        store = HashStore.read(root)

        {findings, _reported_modules} =
          Enum.reduce(bindings, {[], MapSet.new()}, fn binding, {acc, reported} ->
            {binding_findings, reported} = check_binding(binding, context, store, reported)
            {acc ++ binding_findings, reported}
          end)

        findings
    end
  end

  defp check_binding(%{mfa: mfa} = binding, _context, store, reported) do
    case hash(mfa) do
      {:ok, current} ->
        findings =
          case HashStore.fetch(store, @tier, mfa) do
            nil -> []
            committed when committed == current -> []
            _ -> [drift_finding(binding, current)]
          end

        {findings, reported}

      {:error, {:debug_info_stripped, mod}} ->
        if MapSet.member?(reported, mod) do
          {[], reported}
        else
          {[detector_unavailable_finding(binding, mod)], MapSet.put(reported, mod)}
        end

      {:error, {:not_found, details}} ->
        {[dangling_finding(binding, details)], reported}
    end
  end

  defp drift_finding(binding, current) do
    %{
      "code" => @drift_code,
      "tier" => @tier,
      "subject_id" => binding.subject_id,
      "requirement_id" => Map.get(binding, :requirement_id),
      "mfa" => binding.mfa,
      "current_hash" => Base.encode16(current, case: :lower),
      "message" =>
        "expanded_behavior hash for #{binding.mfa} differs from committed value " <>
          "(subject=#{binding.subject_id})"
    }
  end

  defp dangling_finding(binding, details) do
    %{
      "code" => @dangling_code,
      "tier" => @tier,
      "subject_id" => binding.subject_id,
      "requirement_id" => Map.get(binding, :requirement_id),
      "mfa" => binding.mfa,
      "message" =>
        "Declared expanded_behavior binding #{binding.mfa} is not defined " <>
          "(subject=#{binding.subject_id}, tier=#{@tier}). " <>
          "Update realized_by or restore the function. " <>
          "Searched: #{inspect(Map.get(details, :searched, [:beam]))}"
    }
  end

  defp detector_unavailable_finding(binding, mod) do
    %{
      "code" => @detector_unavailable_code,
      "reason" => "debug_info_stripped",
      "tier" => @tier,
      "subject_id" => binding.subject_id,
      "module" => inspect(mod),
      "message" =>
        "expanded_behavior cannot hash #{inspect(mod)}: beam has no debug_info " <>
          "(likely @compile {:no_debug_info, true}). Subject not considered drifted on this tier."
    }
  end

  defp parse_mfa(mfa_string) do
    case Binding.parse(mfa_string) do
      {:ok, {mod, fun, arity}} -> {:ok, {mod, fun, arity}}
      {:ok, {:module, _}} -> {:error, :invalid_mfa}
      {:error, :invalid_mfa, _} -> {:error, :invalid_mfa}
    end
  end

  defp beam_binary_for(mod) do
    case :code.get_object_code(mod) do
      {^mod, binary, _filename} ->
        {:ok, binary}

      :error ->
        case :code.which(mod) do
          path when is_list(path) -> File.read(List.to_string(path))
          path when is_binary(path) -> File.read(path)
          _ -> {:error, :no_beam}
        end
    end
  end

  defp ensure_debug_info(mod, binary) do
    case :beam_lib.chunks(binary, [:debug_info]) do
      {:ok, {^mod, chunks}} ->
        case List.keyfind(chunks, :debug_info, 0) do
          {:debug_info, :none} ->
            {:error, {:debug_info_stripped, mod}}

          {:debug_info, {:debug_info_v1, _backend, :none}} ->
            {:error, {:debug_info_stripped, mod}}

          {:debug_info, {:debug_info_v1, _backend, _data}} ->
            :ok

          _ ->
            {:error, {:debug_info_stripped, mod}}
        end

      {:error, :beam_lib, {:missing_chunk, _, _}} ->
        {:error, {:debug_info_stripped, mod}}

      _ ->
        {:error, {:debug_info_stripped, mod}}
    end
  end

  defp extract_expanded_clause(mod, binary, fun, arity, mfa_string) do
    with {:ok, {^mod, chunks}} <- :beam_lib.chunks(binary, [:debug_info]),
         {:debug_info, {:debug_info_v1, backend, data}} <-
           List.keyfind(chunks, :debug_info, 0),
         {:ok, module_map} when is_map(module_map) <-
           backend.debug_info(:elixir_v1, mod, data, []) do
      case find_definition(module_map, fun, arity) do
        {:ok, ast} -> {:ok, ast}
        :error -> {:error, {:not_found, %{mfa: mfa_string, searched: [:beam_debug_info]}}}
      end
    else
      _ -> {:error, {:not_found, %{mfa: mfa_string, searched: [:beam_debug_info]}}}
    end
  end

  defp find_definition(%{definitions: definitions}, fun, arity) do
    Enum.find_value(definitions, :error, fn
      {{^fun, ^arity}, _kind, _meta, clauses} when clauses != [] ->
        stripped = Enum.map(clauses, fn {_meta, args, guards, body} -> {args, guards, body} end)
        {:ok, {:__expanded__, fun, arity, stripped}}

      _ ->
        nil
    end)
  end

  defp find_definition(_, _, _), do: :error
end
