# agentic-worktree: module=host-elixir version=0.23.0
# Generated by sync-worktree-workflow. Edit the source in agentic-dotfiles,
# then re-run the sync script. Keep repo-specific overrides in Makefile
# before: include make/worktree.mk

# agentic-worktree-source: module=host-elixir version=0.2.1

.PHONY: worktree-profile-bootstrap worktree-profile-smoke worktree-profile-info worktree-profile-before-cleanup

worktree-profile-bootstrap:
	@if [ -f mix.exs ]; then \
		mix deps.get; \
		$(RECURSIVE_MAKE) smoke; \
	else \
		echo "No mix.exs found; skipping Elixir bootstrap"; \
	fi

worktree-profile-smoke:
	@if [ ! -f mix.exs ]; then echo "mix.exs not found"; exit 1; fi
	@mix compile --warnings-as-errors
	@mix test --max-failures 1

worktree-profile-info:
	@printf "%bProfile:%b          host-elixir\n" "$(WT_BOLD)" "$(WT_RESET)"

worktree-profile-before-cleanup:
	@:

# agentic-worktree-source: module=base version=0.7.0
#
# Shared worktree Make targets. This file is concatenated with one profile module
# into repo-local make/worktree.mk by sync-worktree-workflow.

# 1Password account used by any target that calls `op` (e.g. `make env` that
# does `op inject -i .env.tpl -o .env`). The `op` CLI honors the OP_ACCOUNT
# env var, so exporting it makes every bare `op` invocation in any target
# inherit this account — no need to refactor targets to use $(OP). $(OP) is
# also provided for explicit/portable use. Override per-repo if your secrets
# live in a different account.
OP_ACCOUNT ?= team-chapterspot
OP ?= op --account $(OP_ACCOUNT)
export OP_ACCOUNT

RECURSIVE_MAKE ?= $(MAKE)
MAIN_BRANCH ?= main
WORKTREE_ROOT ?= ..
WORKTREE_CLEANUP_BASE ?= HEAD
WORKTREE_PRIMARY_PATH ?= $(shell git worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $$2; exit}')
WORKTREE_PROJECT ?= $(notdir $(WORKTREE_PRIMARY_PATH))
WORKTREE_NAME ?= $(notdir $(CURDIR))
WORKTREE_IS_PRIMARY ?= $(shell [ "$$(cd "$(CURDIR)" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ] && echo yes || echo no)
WORKTREE_CLEANUP_BASE_REV ?= $(shell git rev-parse "$(WORKTREE_CLEANUP_BASE)" 2>/dev/null || printf '%s' "$(WORKTREE_CLEANUP_BASE)")
# SEED_FROM — optional path to a parent worktree to seed host deps and source
# mtimes from at bootstrap. `worktree-new` sets this automatically to the
# directory it was invoked from (the worktree that created the new one). When
# set, `worktree-seed-host` rsyncs deps/ from SEED_FROM, then walks tracked
# files and `touch -r`s each one to match SEED_FROM's mtime. The mtime alignment
# is for copied container _build/ volume reuse only; it does not avoid the first
# host compile. Host _build/ is intentionally not copied: Mix manifests embed
# absolute checkout paths and do not relocate cleanly between worktrees.
# Container _build/deps volume seeding is handled by docker-compose-elixir's
# `worktree-seed-container`.
# Unset disables seeding.
SEED_FROM ?=
# WORKTREE_NEW_PRECHECK_TARGET — optional advisory target worktree-new runs in
# the CURRENT checkout before creating a worktree, so a missing or stale seed
# source is loud at creation time instead of silently degrading bootstrap
# (each seed target no-ops when its source is absent). Profile modules set it
# (docker-compose-elixir → worktree-primary-check); empty disables. Advisory
# only: a precheck failure never blocks worktree creation.
WORKTREE_NEW_PRECHECK_TARGET ?=
# worktree-env-from-parent — copy SEED_FROM's already-materialized .env into
# the new worktree instead of re-running the consumer's secret-store target
# (typically `make env` that calls `op inject -i .env.tpl -o .env`). Secrets
# from a 1Password / AWS Secrets Manager / etc. round-trip are identical
# across worktrees of the same project, so re-deriving them on every new
# worktree is wasted work — and it breaks unattended bootstrap when the
# secret store requires human approval. The parent's worktree-specific tail
# (everything from the first line matching WORKTREE_ENV_SUPPLEMENTAL_MARKER)
# is stripped before the local .env.supplemental is appended, so the
# consumer's `init-worktree` (or equivalent) still controls per-worktree
# overrides like host port and Compose hostnames.
#
# Falls back to running $(WORKTREE_ENV_FALLBACK_TARGET) when SEED_FROM is
# empty or the parent .env is missing (first-ever bootstrap from a cold
# primary checkout). Opt in by replacing `env` with `worktree-env-from-parent`
# in the consumer's WORKTREE_BOOTSTRAP_TARGETS; the consumer's own `env`
# target stays in the Makefile as the fallback.
WORKTREE_ENV_FILE ?= .env
WORKTREE_ENV_SUPPLEMENTAL ?= .env.supplemental
WORKTREE_ENV_SUPPLEMENTAL_MARKER ?= ^\# Worktree:
WORKTREE_ENV_FALLBACK_TARGET ?= env
WORKTREE_COLOR ?= auto
# Colors enabled unless explicitly disabled. We can't detect TTY from inside
# $(shell ...) (it's always a pipe), and MAKE_TERMOUT only appears when Make's
# stdout is a terminal — so default to on and let NO_COLOR / "never" opt out.
WORKTREE_COLOR_ENABLED ?= $(shell if [ "$(WORKTREE_COLOR)" = "never" ] || [ -n "$(NO_COLOR)" ] || [ -n "$$NO_COLOR" ]; then echo no; else echo yes; fi)

ifeq ($(WORKTREE_COLOR_ENABLED),yes)
WT_BOLD := \033[1m
WT_DIM := \033[90m
WT_GREEN := \033[32m
WT_YELLOW := \033[33m
WT_RED := \033[31m
WT_CYAN := \033[36m
WT_RESET := \033[0m
else
WT_BOLD :=
WT_DIM :=
WT_GREEN :=
WT_YELLOW :=
WT_RED :=
WT_CYAN :=
WT_RESET :=
endif

.PHONY: worktree-new worktree-bootstrap smoke worktree-status worktree-info worktree-cleanup worktree-cleanup-all worktree-prune
.PHONY: worktree-seed-host worktree-env-from-parent
.PHONY: wtn wtb wts wti wtc wtca

worktree-new: ## Create + bootstrap a new worktree from the current checkout. Usage: make worktree-new BRANCH=feature/x
	@if [ -z "$(BRANCH)" ]; then \
		echo "Usage: make worktree-new BRANCH=feature/my-feature"; \
		exit 1; \
	fi
	@if [ -n "$(WORKTREE_NEW_PRECHECK_TARGET)" ]; then \
		$(RECURSIVE_MAKE) --no-print-directory $(WORKTREE_NEW_PRECHECK_TARGET) || true; \
	fi
	@SLUG=$$(printf '%s\n' "$(BRANCH)" | sed 's|.*/||; s|[^a-zA-Z0-9]|-|g; s|^-*||; s|-*$$||'); \
	if [ -z "$$SLUG" ]; then echo "Could not derive worktree slug from BRANCH=$(BRANCH)"; exit 1; fi; \
	DIR="$(WORKTREE_ROOT)/$(WORKTREE_PROJECT)-$$SLUG"; \
	if [ -e "$$DIR" ]; then echo "$$DIR already exists"; exit 1; fi; \
	printf "%b\n" "$(WT_BOLD)Creating worktree$(WT_RESET) $$DIR for branch $(WT_CYAN)$(BRANCH)$(WT_RESET) from current HEAD"; \
	git worktree add "$$DIR" -b "$(BRANCH)" HEAD && \
	$(RECURSIVE_MAKE) -C "$$DIR" SEED_FROM="$(CURDIR)" worktree-bootstrap

# fd-inheritance wedge guard (see worktree-bootstrap / smoke below).
#
# Bootstrap and smoke run app-booting steps — `mix compile`/`mix test`, a server
# warmup, anything that starts the runtime. Those steps spawn children (epmd, a
# Phoenix/esbuild watcher, a `Port.open` follower like spire-client's
# TranscriptWatcher `tail -f`) that inherit the recipe's open fds. If the recipe's
# stdout is a PIPE — which is exactly the case when an agent/harness runs
# `make worktree-new ... | tail` or captures `make smoke` — and one of those
# children outlives the BEAM (orphaning to PID 1 on a hard exit) while still
# holding the pipe's write end, the pipe never reaches EOF. The consumer blocks
# forever and the command "hangs" even though the real work finished long ago.
#
# The fix: when stdout is NOT a terminal, run the app-booting subtree with its
# fds pointed at a regular file instead of the inherited pipe. A file has no
# reader to block, so an orphan holding a file fd is harmless; the pipe gets EOF
# as soon as the make tree itself exits. We then cat the log so output is
# preserved, and propagate the real exit code. On a TTY we stream normally —
# a terminal never blocks on EOF, so it is already safe. `[ -t 1 ]` is reliable
# here because a recipe runs with make's actual fd 1 (unlike $(shell ...), which
# is always a pipe — see WORKTREE_COLOR_ENABLED above).
worktree-bootstrap: ## Idempotent standup inside a linked worktree.
	@if [ "$(WORKTREE_IS_PRIMARY)" = "yes" ]; then \
		echo "worktree-bootstrap must run from a linked worktree, not the primary checkout"; \
		exit 1; \
	fi
	@if [ -t 1 ]; then \
		$(RECURSIVE_MAKE) worktree-seed-host worktree-profile-bootstrap; \
	else \
		log="$(CURDIR)/.worktree-bootstrap.log"; \
		$(RECURSIVE_MAKE) worktree-seed-host worktree-profile-bootstrap </dev/null >"$$log" 2>&1; \
		rc=$$?; \
		cat "$$log"; \
		rm -f "$$log"; \
		exit $$rc; \
	fi

# worktree-seed-host — at moment-0 of a new worktree, copy host deps/ from
# SEED_FROM (typically the parent worktree that ran `worktree-new`) and align
# tracked source file mtimes to match. This avoids refetching dependency
# checkouts and makes seeded container _build/ manifests see source files with
# the same mtimes as the parent. This mtime alignment is not a host compile
# optimization; every new host worktree still gets its own first compile. Host
# Mix _build/ is deliberately not copied because host Mix manifests contain
# absolute checkout paths and recompile when moved to a different worktree.
#
# Skipped when SEED_FROM is empty (e.g. running `worktree-bootstrap` by hand on
# an existing worktree). Skipped when SEED_FROM doesn't exist or is the current
# directory. Skipped when no `deps/` exists in SEED_FROM.
worktree-seed-host: ## Seed host deps/ and source mtimes from SEED_FROM.
	@if [ -z "$(SEED_FROM)" ]; then \
		exit 0; \
	fi; \
	if [ ! -d "$(SEED_FROM)" ]; then \
		printf "%b\n" "$(WT_YELLOW)worktree-seed-host: SEED_FROM=$(SEED_FROM) does not exist; skipping$(WT_RESET)"; \
		exit 0; \
	fi; \
	SEED_ABS=$$(cd "$(SEED_FROM)" 2>/dev/null && pwd -P); \
	HERE=$$(pwd -P); \
	if [ "$$SEED_ABS" = "$$HERE" ]; then \
		printf "%b\n" "$(WT_YELLOW)worktree-seed-host: SEED_FROM is the current worktree; skipping$(WT_RESET)"; \
		exit 0; \
	fi; \
	if ! command -v rsync >/dev/null 2>&1; then \
		printf "%b\n" "$(WT_YELLOW)worktree-seed-host: rsync not on PATH; skipping$(WT_RESET)"; \
		exit 0; \
	fi; \
	if [ -d "$$SEED_ABS/deps" ]; then \
		printf "%b\n" "→ Seeding deps/ from $(SEED_FROM)"; \
		mkdir -p deps; \
		rsync -a --delete "$$SEED_ABS/deps/" deps/; \
		printf "%b\n" "  $(WT_GREEN)✓ deps/ seeded$(WT_RESET)"; \
	fi; \
	printf "%b\n" "→ Aligning tracked source mtimes for container _build reuse from $(SEED_FROM)"; \
	tmp=$$(mktemp); \
	git ls-files > "$$tmp" 2>/dev/null || : > "$$tmp"; \
	touched=0; missing=0; \
	while IFS= read -r f; do \
		if [ -e "$$SEED_ABS/$$f" ] && [ -e "$$f" ]; then \
			if touch -r "$$SEED_ABS/$$f" "$$f" 2>/dev/null; then \
				touched=$$((touched + 1)); \
			else \
				missing=$$((missing + 1)); \
			fi; \
		else \
			missing=$$((missing + 1)); \
		fi; \
	done < "$$tmp"; \
	rm -f "$$tmp"; \
	printf "  $(WT_GREEN)✓ %s files aligned$(WT_RESET)" "$$touched"; \
	if [ "$$missing" -gt 0 ]; then printf " (%s skipped)" "$$missing"; fi; \
	printf "\n"

# worktree-env-from-parent — see the var block above for the full rationale.
# In short: copy SEED_FROM's .env (already-materialized secrets), strip its
# worktree-specific tail, append the local .env.supplemental so the new
# worktree's per-worktree overrides win. Falls through to the consumer's
# secret-store target (default: `env`) when there's nothing to copy from.
worktree-env-from-parent: ## Seed $(WORKTREE_ENV_FILE) from SEED_FROM; fall back to $(WORKTREE_ENV_FALLBACK_TARGET).
	@if [ -z "$(SEED_FROM)" ]; then \
		printf "%b\n" "$(WT_DIM)worktree-env-from-parent: SEED_FROM empty; running '$(WORKTREE_ENV_FALLBACK_TARGET)' to materialize $(WORKTREE_ENV_FILE)$(WT_RESET)"; \
		$(RECURSIVE_MAKE) "$(WORKTREE_ENV_FALLBACK_TARGET)"; \
	else \
		SEED_ABS=$$(cd "$(SEED_FROM)" 2>/dev/null && pwd -P); \
		if [ -z "$$SEED_ABS" ] || [ ! -f "$$SEED_ABS/$(WORKTREE_ENV_FILE)" ]; then \
			printf "%b\n" "$(WT_YELLOW)worktree-env-from-parent: $(SEED_FROM)/$(WORKTREE_ENV_FILE) missing; running '$(WORKTREE_ENV_FALLBACK_TARGET)'$(WT_RESET)"; \
			$(RECURSIVE_MAKE) "$(WORKTREE_ENV_FALLBACK_TARGET)"; \
			exit 0; \
		fi; \
		HERE=$$(pwd -P); \
		if [ "$$SEED_ABS" = "$$HERE" ]; then \
			printf "%b\n" "$(WT_YELLOW)worktree-env-from-parent: SEED_FROM is the current worktree; skipping$(WT_RESET)"; \
			exit 0; \
		fi; \
		printf "%b\n" "→ Seeding $(WORKTREE_ENV_FILE) from $$SEED_ABS/$(WORKTREE_ENV_FILE)"; \
		awk -v marker='$(WORKTREE_ENV_SUPPLEMENTAL_MARKER)' '$$0 ~ marker {exit} {print}' "$$SEED_ABS/$(WORKTREE_ENV_FILE)" > "$(WORKTREE_ENV_FILE)"; \
		if [ -f "$(WORKTREE_ENV_SUPPLEMENTAL)" ]; then \
			cat "$(WORKTREE_ENV_SUPPLEMENTAL)" >> "$(WORKTREE_ENV_FILE)"; \
		fi; \
		printf "%b\n" "  $(WT_GREEN)✓ $(WORKTREE_ENV_FILE) seeded from parent (no $(WORKTREE_ENV_FALLBACK_TARGET) round-trip)$(WT_RESET)"; \
	fi

smoke: ## Verify the worktree is ready for implementation.
	@if [ -t 1 ]; then \
		$(RECURSIVE_MAKE) worktree-profile-smoke; \
	else \
		log="$(CURDIR)/.worktree-smoke.log"; \
		$(RECURSIVE_MAKE) worktree-profile-smoke </dev/null >"$$log" 2>&1; \
		rc=$$?; \
		cat "$$log"; \
		rm -f "$$log"; \
		exit $$rc; \
	fi

ifndef WORKTREE_PROFILE_PROVIDES_STATUS
worktree-status: ## Show all worktrees with branch and git status.
	@printf "\n  %b%-44s %-40s %s%b\n\n" "$(WT_BOLD)" "WORKTREE" "BRANCH" "GIT" "$(WT_RESET)"
	@git worktree list --porcelain | awk '/^worktree /{path=$$2} /^branch /{branch=$$2; print path "\t" branch}' | \
	while IFS=$$'\t' read -r wpath branch; do \
		name=$$(basename "$$wpath"); \
		short_branch=$$(printf '%s\n' "$$branch" | sed 's|refs/heads/||'); \
		dirty=$$(git -C "$$wpath" status --porcelain 2>/dev/null | wc -l | tr -d ' '); \
		unmerged=$$(git -C "$$wpath" rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$short_branch" --count 2>/dev/null || echo "?"); \
		git_info=""; \
		if [ "$$dirty" != "0" ]; then git_info="$(WT_YELLOW)$$dirty dirty$(WT_RESET)"; fi; \
		if [ "$$unmerged" = "0" ]; then \
			if [ -n "$$git_info" ]; then git_info="$(WT_GREEN)merged$(WT_RESET), $$git_info"; else git_info="$(WT_GREEN)merged$(WT_RESET)"; fi; \
		else \
			if [ -n "$$git_info" ]; then git_info="$(WT_CYAN)$$unmerged unmerged$(WT_RESET), $$git_info"; else git_info="$(WT_CYAN)$$unmerged unmerged$(WT_RESET)"; fi; \
		fi; \
		printf "  %-44s %-40s %b\n" "$$name" "$$short_branch" "$$git_info"; \
	done; \
	echo ""
endif

worktree-info: ## Display current worktree configuration.
	@printf "%bProject:%b          %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_PROJECT)"
	@printf "%bWorktree name:%b    %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_NAME)"
	@printf "%bPath:%b             %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(CURDIR)"
	@printf "%bPrimary checkout:%b %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_PRIMARY_PATH)"
	@printf "%bIs primary:%b       %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_IS_PRIMARY)"
	@printf "%bCleanup base:%b     %s (%s)\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_CLEANUP_BASE)" "$(WORKTREE_CLEANUP_BASE_REV)"
	@$(RECURSIVE_MAKE) worktree-profile-info

worktree-cleanup: ## Remove one merged worktree. Usage: make worktree-cleanup NAME=<name> | DIR=<path> [FORCE=1]
	@if [ -z "$(NAME)$(DIR)" ]; then \
		echo "Usage: make worktree-cleanup NAME=<worktree-name> [FORCE=1]"; \
		echo "   or: make worktree-cleanup DIR=<path-to-worktree> [FORCE=1]"; \
		echo ""; \
		echo "NAME resolves under WORKTREE_ROOT ($(WORKTREE_ROOT)). Use DIR for a linked"; \
		echo "worktree that lives anywhere else (a scratch dir, /tmp, a sibling tree) so"; \
		echo "teardown still runs the profile hook instead of a hand-rolled rm -rf."; \
		exit 1; \
	fi
	@if [ -n "$(DIR)" ]; then DIR="$(DIR)"; else DIR="$(WORKTREE_ROOT)/$(NAME)"; fi; \
	CLEANUP_NAME="$(NAME)"; [ -n "$$CLEANUP_NAME" ] || CLEANUP_NAME=$$(basename "$$DIR"); \
	if [ ! -d "$$DIR" ]; then echo "$$DIR does not exist"; exit 1; fi; \
	if [ "$$(cd "$$DIR" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ]; then \
		echo "Refusing to remove primary checkout $$DIR"; exit 1; \
	fi; \
	DIRTY=$$(git -C "$$DIR" status --porcelain 2>/dev/null); \
	if [ -n "$$DIRTY" ]; then \
		if [ -n "$(FORCE)" ]; then \
			printf "%b\n" "$(WT_YELLOW)$$DIR is dirty; FORCE=1 set, discarding:$(WT_RESET)"; \
			printf '%s\n' "$$DIRTY" | sed 's/^/  /'; \
		else \
			echo "$$DIR is dirty; commit or stash first (or re-run with FORCE=1)"; exit 1; \
		fi; \
	fi; \
	BRANCH=$$(git -C "$$DIR" rev-parse --abbrev-ref HEAD); \
	UNMERGED=$$(git rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$BRANCH" --count 2>/dev/null || echo "?"); \
	if [ "$$UNMERGED" != "0" ]; then \
		if [ -n "$(FORCE)" ]; then \
			printf "%b\n" "$(WT_YELLOW)$$BRANCH has $$UNMERGED commits not merged into $(WORKTREE_CLEANUP_BASE); FORCE=1 set, deleting branch with -D$(WT_RESET)"; \
		else \
			echo "$$BRANCH has $$UNMERGED commits not merged into $(WORKTREE_CLEANUP_BASE); refusing (or re-run with FORCE=1)"; exit 1; \
		fi; \
	fi; \
	$(RECURSIVE_MAKE) worktree-profile-before-cleanup NAME="$$CLEANUP_NAME"; \
	printf "%b\n" "Removing worktree $(WT_CYAN)$$DIR$(WT_RESET) (branch $(WT_CYAN)$$BRANCH$(WT_RESET))"; \
	if [ -n "$(FORCE)" ]; then \
		git worktree remove --force "$$DIR" && git branch -D "$$BRANCH"; \
	else \
		git worktree remove "$$DIR" && git branch -d "$$BRANCH"; \
	fi

worktree-cleanup-all: ## Remove every merged worktree. FORCE=1 also removes dirty/unmerged worktrees.
	@git worktree list --porcelain | awk '/^worktree /{path=$$2} /^branch /{branch=$$2; print path "\t" branch}' | \
	while IFS=$$'\t' read -r wpath branch; do \
		name=$$(basename "$$wpath"); \
		short_branch=$$(printf '%s\n' "$$branch" | sed 's|refs/heads/||'); \
		if [ "$$(cd "$$wpath" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ]; then continue; fi; \
		if [ "$$short_branch" = "$$(git rev-parse --abbrev-ref HEAD)" ]; then continue; fi; \
		dirty=$$(git -C "$$wpath" status --porcelain 2>/dev/null | wc -l | tr -d ' '); \
		unmerged=$$(git rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$short_branch" --count 2>/dev/null || echo "?"); \
		if [ -n "$(FORCE)" ] || { [ "$$dirty" = "0" ] && [ "$$unmerged" = "0" ]; }; then \
			$(RECURSIVE_MAKE) worktree-cleanup NAME="$$name" DIR="$$wpath" FORCE="$(FORCE)"; \
		fi; \
	done

worktree-prune: ## Prune git metadata for missing worktree directories.
	@git worktree prune -v

wtn: worktree-new ## Alias for worktree-new
wtb: worktree-bootstrap ## Alias for worktree-bootstrap
wts: worktree-status ## Alias for worktree-status
wti: worktree-info ## Alias for worktree-info
wtc: worktree-cleanup ## Alias for worktree-cleanup
wtca: worktree-cleanup-all ## Alias for worktree-cleanup-all
